---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: openshift-image-registry
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: image-registry-operator-networkpolicy
  namespace: openshift-image-registry
spec:
  ingress:
  # allow ingress from monitoring
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-monitoring
    ports:
    - port: 60000
      protocol: TCP

  egress:
  # allow egress to kube-apiserver
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-kube-apiserver
      podSelector:
        matchLabels:
          app: openshift-kube-apiserver
    ports:
    - protocol: TCP
      port: 6443

  podSelector:
    matchLabels:
      name: cluster-image-registry-operator
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: image-registry-networkpolicy
  namespace: openshift-image-registry
spec:
  ingress:
  # allow ingress from monitoring
  - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: openshift-monitoring
    ports:
    - port: 5000
      protocol: TCP

  egress:
  
  # allow egress to kube-apiserver
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-kube-apiserver
      podSelector:
        matchLabels:
          app: openshift-kube-apiserver
    ports:
    - protocol: TCP
      port: 6443

  # allow egress to DNS
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-dns
      podSelector:
        matchLabels:
          dns.operator.openshift.io/daemonset-dns: default
    ports:
    - protocol: TCP
      port: 5353
    - protocol: UDP
      port: 5353

  # allow egress to ONLY internet (external)
  # why? i.e. S3 access
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        # refine the rule with the private network exception
        except:
        - 10.0.0.0/8     # RFC1918: Block access towards other private internal networks
        - 172.16.0.0/12  # RFC1918: Block access towards other private internal networks
        - 192.168.0.0/16 # RFC1918: Block access towards other private internal networks
    ports:
    - protocol: TCP
      port: 443
      
  podSelector:
    matchLabels:
      docker-registry: default
  policyTypes:
  - Ingress
  - Egress